#!/usr/bin/python

for i in xrange(1,6):
	for j in xrange(5):
		ques = open("questions/{0}.{1}.md".format(str(100*i),str(j)),"w")
		ques.close()
		ans = open("answers/{0}.{1}.md".format(str(100*i),str(j)),"w")
		ans.close()
